### ISSUE TITLE
Issues with `Calc_Kmeans`

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [James-Thorson/FishStatsUtils#1]
2 issues with [`Calc_Kmeans`](https://github.com/James-Thorson/FishStatsUtils/blob/master/R/Calc_Kmeans.R):
  * the `randomseed` argument does not lead to the same knot locations being generated if you rerun the function and
  * `nstart` is hard coded to a value of one rather than using the argument.

**Comment by James-Thorson** [comment]
please provide `randomseed` value for now, and `nstart` input is used but in a hand-coded loop not `stats::kmeans` to allow better user messaging.

**Comment by kellijohnson-NOAA** [comment]
Okay, I didn't realize that your loop was doing the same thing as `nstart`.
WRT `randomseed`, it doesn't work. I ran this code
```
set.seed(1)
Kmeans = list( "tot.withinss"=Inf )
for(i in 1:nstart){
         Tmp = stats::kmeans(x=loc_orig, centers=n_x, iter.max=iter.max, nstart=1, trace=0)
        if(Tmp$tot.withinss < Kmeans$tot.withinss ){Kmeans=Tmp}
 }
str(Tmp)
```
2x and you do not get the same answer each time. I cannot find a way to reproduce the Kmeans if I did not save it.

**Comment by kellijohnson-NOAA** [comment]
The reason I was not getting a reproducible result was the nstart in the `stats::kmeans` was not set to 1. Instead, I had it set to `nstart` as below.
```
set.seed(1)
Kmeans = list( "tot.withinss"=Inf )
for(i in 1:nstart){
         Tmp = stats::kmeans(x=loc_orig, centers=n_x, iter.max=iter.max, nstart=nstart, trace=0)
        if(Tmp$tot.withinss < Kmeans$tot.withinss ){Kmeans=Tmp}
 }
str(Tmp)
```
So `Calc_Kmeans` is reproducible as long as you specify `randomseed`.

**Comment by James-Thorson** [comment]
Also FYI, it appears that `randomseed=1` is the default behavior in the current version, you might double check that you're using the most up-to-date version
