### ISSUE TITLE
Region="other" in  make_extrapolation_info

### ISSUE THREAD

**Issue by aastarloa** [James-Thorson/FishStatsUtils#10]
Hello, 
I'm trying to fit my model by using Region="other" but I'm getting this error despite having already defined observations_LL:

Making extrapolation-grid
convUL: For the UTM conversion, automatically detected zone 29.
convUL: Converting coordinates within the northern hemisphere.
Error in (function (Region, zone = NA, strata.limits = data.frame(STRATA = "All_areas"),  : 
  Because you're using a new Region[rI], please provide 'observations_LL' input

This is my code:
_Make settings_
settings = make_settings( n_x=50, Region="other", purpose="index", strata.limits=data.frame(STRATA="All_areas"))

_Fit model_
fit1 = fit_model( "settings"=settings, "Lat_i"=del$Lat, 
                 "Lon_i"=del$Lon, "t_i"=del$Year, 
                 "c_i"=rep(0,nrow(del)), "b_i"=del$Encounter, 
                 "a_i"=del$Dist.km, 
                 model_args=list("ObsModel_ez[e,1]"=5),
                 extrapolation_args = make_extrapolation_info(Region="other",
                                                              strata.limits=data.frame(STRATA="All_areas"),
                                                              observations_LL=del[ ,c("Lon","Lat")]))

Thank you in advance

**Comment by James-Thorson** [comment]
Please try:

```R
fit1 = fit_model( "settings"=settings, "Lat_i"=del$Lat,
"Lon_i"=del$Lon, "t_i"=del$Year,
"c_i"=rep(0,nrow(del)), "b_i"=del$Encounter,
"a_i"=del$Dist.km,
model_args=list("ObsModel_ez[e,1]"=5),
extrapolation_args = list(observations_LL=del[ ,c("Lon","Lat")]))
```

and report back whether it fixes it.

**Comment by aastarloa** [comment]
Fixed! Thank you very much

**Comment by James-Thorson** [comment]
You'll also need to change how you're specifying `ObsModel_ez` either by editing its value in `settings`, or by changing your specification to input `model_args`

**Comment by aastarloa** [comment]
Rigth. Already done. Thank you again
