### ISSUE TITLE
Required packages 'pander' and 'formatR' are not installed if missing

### ISSUE THREAD

**Issue by John-R-Wallace-NOAA** [James-Thorson/FishStatsUtils#2]
Downloading GitHub repo james-thorson/VAST@master
...

ERROR: dependencies 'pander', 'formatR' are not available for package 'FishStatsUtils'

* removing 'W:/MRO/MRO/library/FishStatsUtils'

Installation failed: ...

**Comment by James-Thorson** [comment]
Could you elaborate?  Is this error message saying that the version of MRO you're using is too old to have a downloadable version of pander and formatR, or that these need to be added as dependencies, or ...?

I suggest updating to a later version of MRO to see if that fixes it.
