### ISSUE TITLE
Bug in plot_biomass_index when using combined model

### ISSUE THREAD

**Issue by colemonnahan** [James-Thorson/FishStatsUtils#23]
When using the combined feature, that is when c_iz is more than a single column, the plot function `plot_biomass_index` fails:

````
Error in tapply(TmbData$b_i, INDEX = list(factor(TmbData$c_i, levels = 1:TmbData$n_c -  : 
  arguments must have same length
````

Which is on this line: https://github.com/James-Thorson-NOAA/FishStatsUtils/blob/master/R/plot_biomass_index.R#L210

If I change it to `TmbData$c_i[,1]` then that code chunk runs, but it's not clear to me how to handle this situation. I also tried setting `settings$Options$treat_nonencounter_as_zero <- FALSE` to skip that calculation which resulted in this error:

````
Error in Mat_xt[, Years2Include, drop = FALSE] : 
  incorrect number of dimensions
````

with this traceback

````
4: plot_variable(Y_gt = Mat_xt[, Years2Include, drop = FALSE], map_list = list(PlotDF = PlotDF, 
       MapSizeRatio = MapSizeRatio), projargs = projargs, working_dir = working_dir, 
       panel_labels = Year_Set[Years2Include], file_name = file_name, 
       n_cells = n_cells, ...)
3: (function (plot_set = 3, Report, PlotDF, Sdreport = NULL, TmbData = NULL, 
       projargs = "+proj=longlat", Panel = "Category", Year_Set = NULL, 
       Years2Include = NULL, category_names = NULL, quiet = FALSE, 
       working_dir = paste0(getwd(), "/"), MapSizeRatio, n_cells, 
       ...) 
    ...
2: do.call(what = plot_maps, args = plot_maps_args)
1: plot_results(fit, plot_set = 2)
````

I wonder if it's better just to use my own plotting code when demonstrating the combined feature? Or do you want `plot_results` to work for this model type? @James-Thorson-NOAA

**Comment by James-Thorson-NOAA** [comment]
Cole, 

could you see if the development branch of FishStatsUtils (which I'll push as 2.3.2 sometime soon, to also fix another bug in the formula interface for some specific uses) fixes the `Error in Mat_xt[, Years2Include, drop = FALSE]` message?

If yes, then maybe we have a sufficient solution all around.

**Comment by colemonnahan** [comment]
I installed the latest master branch version. It seems to work now for different model configurations as long as I set `settings$Options$treat_nonencounter_as_zero <- FALSE`
