### ISSUE TITLE
Implementation of fine_scale option in make_map_info 

### ISSUE THREAD

**Issue by embiuw** [James-Thorson/FishStatsUtils#36]
Hi,
I'm trying to use the mapping/plotting functions based on a model fit using fine_scale=T. I get the message that the fine_scale option is not yet implemented in teh mapping functions. Is this correct or am I looking in the wrong place (checked in James-Thorson-NOAA/FishStatsUtils/R/make_map_info.R? 
Cheers,
Martin

**Comment by James-Thorson-NOAA** [comment]
Do you see a packageVersion.txt file and can you copy-paste that?  Or what does packageVersion("VAST") and packageVersion("FishStatsUtils") show?

**Comment by embiuw** [comment]
> packageVersion("VAST")
[1] ‘3.0.0’
> packageVersion("FishStatsUtils")
[1] ‘2.1.0’

**Comment by embiuw** [comment]
Sorry, my mistake. I had not provided a 'spatial_list' object when calling the function. Now it works!
