### ISSUE TITLE
make_covariates drops values

### ISSUE THREAD

**Issue by cstawitz** [James-Thorson/FishStatsUtils#38]
On line 45-46 of `make_covariates` the line `X = model.matrix(update.formula(formula, ~. + 0), data = DF)[, , drop = FALSE]` deletes all of the covariate values. my `DF` is a data frame with 4 variables: `Year, Lat, Lon, CPTemp` where CPTemp is the covariate.

**Comment by James-Thorson-NOAA** [comment]
What did you specify for 'formula'?

**Comment by cstawitz** [comment]
I was calling `make_covariates` from `make_data`, so formula was set to the default because the formula argument to `make_data` is not documented.

**Comment by cstawitz** [comment]
The default for formula in `make_data` is `~0` but it seems like you would want to either set it to be ~covariate_names in `make_data` [here](https://github.com/James-Thorson-NOAA/VAST/blob/67b9acb3aabbbdbb22860d757e2566f6dbc7e7ce/R/make_data.R#L200)  or throw an error if `covariate_data` is specified and `formula` is not, because `~0` just silently deletes the covariates.

**Comment by James-Thorson-NOAA** [comment]
I would love it if you did a pull request to the development branch with proposed doxygen documentation.  However, I see that formula and covariate_data are documented in `make_covariates` and this is then imported to `make_data` so I'm not sure what you think is missing.  I want to maintain the default behavior of `lm` so using `formula=~0` will continue to turn off all covariates.  I also think its a reasonable default, but perhaps we could discuss in person sometime.

**Comment by James-Thorson-NOAA** [comment]
Upon further thought -- I think I like your suggestion Christine about throwing an error whenever covariate_data is supplied but formula is not.  I'll ask other steering committee members (Eric and Cole) their thoughts too.

**Comment by cstawitz** [comment]
Thanks. I see the documentation now on GitHub, I just didn't have it
locally!

**Comment by colemonnahan** [comment]
I think this is the right approach, to let the default be ~0 and override the data input. I think it's dangerous to assume to use all covariates in a matrix that is passed (and their relationship). It's safer to force the user to specify the formula explicitly, and catching an error there is a good way to do that.

I could easily see someone passing a matrix and doing model selection on covariates by having different formulas, and then when you go to put in ~0 to try a version without any, you end up with something very unexpected.

**Comment by James-Thorson-NOAA** [comment]
OK, I just changed `VAST::make_data` and `FishStatsUtils::make_covariates` in their development branches to remove the default value of argument `formula` such that both functions will throw an error if the user specifies `covariates_data` without also specifying `formula`, and will maintain backwards compatibility in the interface by ignoring `formula` if the user doesn't specifying `covariate_data`
