### ISSUE TITLE
proj4string in plot_data leads to warning message with spTransform

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [James-Thorson/FishStatsUtils#50]
When I use `plot_data()` I get a warning message printed to the screen from `sp::spTransform()` of 
```
Warning message:
In spTransform(xSP, CRSobj, ...) :
  NULL source CRS comment, falling back to PROJ string
```
I was able to make this go away by adding the following line of code, which I found in the [spTransform code](https://rdrr.io/cran/rgdal/src/R/project.R), to the [plot_data.R file](https://github.com/James-Thorson-NOAA/FishStatsUtils/blob/master/R/plot_data.R) before transforming the object map_data (i.e., before line 50):
```
comment(map_data@proj4string) <- paste0(slot(slot(map_data, "proj4string"), "projargs"), " +type=crs")
```
I do not necessarily understand projections to the fullest, so please feel free to close this issue without making any changes and I will just use `suppressWarnings(plot_data())`. Before posting this issue, I did some google searching and it appears that the code in `spTransform` that generates the warning message is because of something related to WKT2 (2019), whatever that means. For details see the Details section of the [documentation for spTransform](http://127.0.0.1:10414/library/rgdal/html/spTransform.html). The documentation for [`CRS`](http://127.0.0.1:10414/library/sp/html/CRS-class.html) also talks about it and shows in the example how to add a comment to the projection.

**Comment by James-Thorson-NOAA** [comment]
Thanks Kelli for flagging this.  It also comes up in [VAST issue #244](https://github.com/James-Thorson-NOAA/VAST/issues/244), and is now fixed in the development branch by editing the default projargs generator.  It arises in recent versions of `sp` due to an update from PROJ4 to PROJ6.  In the meantime, the warning is just a nuisance and has no implications

**Comment by kellijohnson-NOAA** [comment]
Thanks for the explanation @James-Thorson-NOAA and sorry I didn't check the VAST issue list.

**Comment by James-Thorson** [comment]
No problem!  When I refactored the code to put utilities in FishStatsUtils,
I never really figured out a good way to consolidate the github wiki and
issue tracker.  Any ideas on that topic?

**Comment by kellijohnson-NOAA** [comment]
I think many repositories are struggling with how to deal with user questions / code development questions across several repositories. I don't feel like there is a good answer yet. The VAST issue list seems to be the go to for most people, where I chose to post my issue here b/c the function was within this package. My main suggestion that I have found helpful is to have lots of tags so that issues can be sorted and viewed using them. That way you can partition out different topics. I personally see the TMB google group as something that is failing. People don't know if they should post to the group or on the issue list and not everyone follows both. I like consolidation. I know github is rolling out a beta version of a forum board called Discussions, e.g., see [here](https://github.com/vercel/vercel/discussions), that will eventually be available in all repositories. I think the best option is to encourage people to use just one repo for the majority of their questions, and here it would be VAST because in theory FishStatsUtils gets installed as a dependency when users install VAST and not the other way around, so some people won't even know that they are using FishStatsUtils.
