### ISSUE TITLE
Very minor change in make_kmeans.R (and wherever relevant)

### ISSUE THREAD

**Issue by Arnaud-Gruss** [James-Thorson/FishStatsUtils#56]
Hi, I'd like to suggest a very minor change in make_kmeans.R (and wherever relevant):
Line 53 (master branch): 
```R
message( "n_x less than n_unique so no calculation necessary" )
```
which should be replaced with:
```R
message( "n_x greater than or equal to n_unique so no calculation necessary" )
```
Thanks a lot!

**Comment by James-Thorson-NOAA** [comment]
I'm changing this message on the development branch of FishStatsUtils, thanks for pointing out that it is phrased incorrectly
