### ISSUE TITLE
Minor issue regarding rotate_factors in the development branch

### ISSUE THREAD

**Issue by Arnaud-Gruss** [James-Thorson/FishStatsUtils#64]
Hello! Just a minor issue regarding rotate_factors in the development branch:
In line 34
```R
Nyears = nrow(L_pj)
```
should be replaced with 
```R
dim(Psi_sjt)[3]
```
Alternatively, line 34 could be deleted, as `Nyears` is not used later in the script. 
Many thanks!

**Comment by James-Thorson-NOAA** [comment]
I'll comment this out in the development branch.  I gather it wasn't actually causing an issue, but you're just trying to clean up the code?  I want it there to indicate what that third element is (which it still does after commenting it out)
