### ISSUE TITLE
Error in summary(fit_model) when what="residuals"

### ISSUE THREAD

**Issue by N-DucharmeBarth** [James-Thorson/FishStatsUtils#72]
Hi Jim, I've come across the following error in the summary function for a _'fit_model'_ object. 

> Error in DHARMa::createDHARMa(simulatedResponse = b_iz, observedResponse = x$data_list$b_i,  : 
  object 'fit' not found

It looks like the error is being thrown from the _DHARMa::createDHARMa_ call in the summary.fit_model function of fit_model.R (line 518)
```{r}
      dharmaRes = DHARMa::createDHARMa(simulatedResponse=b_iz, # + 1e-10*array(rnorm(prod(dim(b_iz))),dim=dim(b_iz)),
        observedResponse=x$data_list$b_i,
        fittedPredictedResponse=fit$Report$D_i,
        integer=FALSE)
```

because `fittedPredictedResponse` is hard coded to look for the global variable 'fit' instead of the local variable 'x'.

Changing line 518 of fit_model.R to 
```{r}
fittedPredictedResponse=x$Report$D_i,
```
should solve the problem but this should be checked by running your https://github.com/James-Thorson-NOAA/VAST/wiki/Index-standardization example with the output from fit_model named something other than 'fit'. It also looks like this same hard coding to an expected global variable 'fit' occurs on lines 540 & 550.

For reference I'm using R version 4.0.3, FishStatsUtils version 2.9.1 and VAST version 3.7.1.

**Comment by James-Thorson-NOAA** [comment]
Thanks for reporting the bug (which threw an uninformative error message).

I have fixed it on the `dev` branch, and feel free to report any further issues with the fix on this thread but I'm closing it for now.

**Comment by N-DucharmeBarth** [comment]
Thanks for the quick fix @James-Thorson-NOAA !!
