### ISSUE TITLE
Dependency installation: plotKML removed from CRAN

### ISSUE THREAD

**Issue by Jason-Conner-NOAA** [James-Thorson/FishStatsUtils#76]
Just a note that the package plotKML has been removed from CRAN and is unavailable for default installation of FishStatsUtils.
https://cran-archive.r-project.org/web/checks/2021/2021-10-06_check_results_plotKML.html

**Comment by James-Thorson-NOAA** [comment]
A quick googling suggests that `raster::rasterize` might do the same thing as `plotKML::vect2rast` as used in `FishStatsUtils::plot_variable`.  Does anyone have time to explore a bit?

**Comment by James-Thorson-NOAA** [comment]
I just spent a quick moment implementing this fix on the dev branch.  I'm closing the issue but happy to hear feedback on implementation here.

**Comment by James-Thorson** [comment]
As a note to myself ... It looks like sp::SpatialPixelsDataFrame could be
an alternative to raster::rasterize ... Could be investigated in the future
if dependency issues continue
