### ISSUE TITLE
suggestion: make map_data an argument to make_mesh

### ISSUE THREAD

**Issue by N-DucharmeBarth-NOAA** [James-Thorson/FishStatsUtils#84]
Hi Jim,
As a suggestion, it could be useful to allow for `map_data` to be an argument to `make_mesh()` in order for the user to pass in a higher resolution land layer. `map_data` could be listed as a formal argument to the function without a default value and the following code could be modified to create `map_data` if a value isn't provided by the user:

```
if(missing(map_data))
{
 map_data = rnaturalearth::ne_countries( scale=switch("medium", "low"=110, "medium"=50, "high"=10, 50) )
  attr(map_data,"proj4string") = sp::CRS("+proj=longlat +datum=WGS84")  
}
```
Best,
Nicholas

**Comment by James-Thorson-NOAA** [comment]
I just added this now to the dev branch.  I'm closing here, but if you have time to check it please provide any updates here.

**Comment by N-DucharmeBarth-NOAA** [comment]
Hi Jim, thanks! I can confirm that passing `map_data` as an argument works as expected for my example.
