### ISSUE TITLE
Possible (?) error in issue check for oneStepAhead residuals in summary.fit_model()

### ISSUE THREAD

**Issue by N-DucharmeBarth-NOAA** [James-Thorson/FishStatsUtils#86]
Hi Jim,
I think I may have found an error in the issue checking for the oneStepAhead residual calculation in `summary.fit_model()`.

On lines 633-635 of [fit_model.R](https://github.com/James-Thorson-NOAA/FishStatsUtils/blob/main/R/fit_model.R), there is a check to make sure that the error structure of the 2nd model component is either a gamma or lognormal distribution.
```
if( !all(x$data_list$ObsModel_ez[1,] %in% c(1,2)) ){
        stop("oneStepAhead residuals only code for gamma and lognormal distributions")
}
```
As currently formulated this looks to see if both the 1st and 2nd model components have options 1 & 2, but only for the first ObsModel specified in the case that multiple data types are used. I think the check should actually be **ObsModel_ez[,1]** on line 633:
```
if( !all(x$data_list$ObsModel_ez[,1] %in% c(1,2)) ){
        stop("oneStepAhead residuals only code for gamma and lognormal distributions")
}
```
I'm currently working with a model where `ObsModel_ez = matrix(c(2,4),nrow=1,ncol=2)`, and when I make the above change I am able to calculate oneStepAhead residuals that look reasonable.
Best,
Nicholas

**Comment by James-Thorson-NOAA** [comment]
Good catch!  Making that change on the dev-branch now.  

Please note that I never investigated OSA-residuals in detail ... Cole and Andrea are working with Kasper and Florian to explore alternative calculations that should be much faster than what's in there currently, and I can't really vouch for the OSA residuals as currently implemented.  Please use with care (if at all)!
