### ISSUE TITLE
Install issues for INLA and FishStatsUtils - maybe INLA or rtools version issue?

### ISSUE THREAD

**Issue by MargaretSiple-NOAA** [James-Thorson/FishStatsUtils#87]
I am trying to re-run last year's GOA flathead sole VAST run and am trying to install the versions of VAST, and FishStatsUtils that were used in 2021. The settings I want are:
R 4.0.2
VAST v3.6.1
FishStatsUtils v2.8.0
cpp VAST_v12_0_0

I have been following [these ](https://github.com/James-Thorson-NOAA/VAST#installation-instructions)"if you're having problems with installation" instructions. I am working in R v4.0.2.

- TMB installation works fine and I have TMB v 1.9.1.
- INLA installation says `Warning in install.packages :
  dependencies ‘Rgraphviz’, ‘graph’ are not available`. The install has non-zero exit status and the message directs me to `/usr/bin/cp --help` but I don't know where that dir is. Is this potentially an 'old version of INLA' thing? I have been fiddling around on and off all day and this is my final tap out of resignation. 

Here's my `sessionInfo()`:

```
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.2 tools_4.0.2
```

**Comment by kellijohnson-NOAA** [comment]
The INLA install website says
```
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install(c("graph", "Rgraphviz"), dep=TRUE)
```

**Comment by James-Thorson-NOAA** [comment]
INLA is definitely a finicky dependency, and some day I'd love help in translating over to alternatives like `package::delauney`.   Unfortunately, I can't support INLA install issues myself, and will likely close here but happy to keep discussing

Does Kelly's suggestion work?

Also, I assume you're doing the hindcast bridging steps, is that right?  If yes, I recommend just updating to the latest numeric release of VAST/FishStatsUtils using those previous settings, and confirming that results are unchanged.  I think the replicating past year with past year's software is not necessary if you can replicate with updated software instead.

**Comment by MargaretSiple-NOAA** [comment]
I think Kelli's solution is working-- it's still installing (taking >20 mins) but I've gotten past where I think I was getting the error earlier.

Jim- I will be doing the hindcast bridging steps too, but my first step was to make sure everything works with last year's run and that all the installations worked. For that step, I'm trying to use the versions of everything that were used last cycle so I can replicate them. Then I'll update everything to the versions in this year's TOR and start with the hindcast.

**Comment by MargaretSiple-NOAA** [comment]
No dice... Kelli's chunk installed `graph` and `Rgraphviz` but when I run `install.packages("INLA", repos=c(getOption("repos"), INLA="https://inla.r-inla-download.org/R/stable"), dep=TRUE)` after that chunk, I get a similar error as before:
![image](https://user-images.githubusercontent.com/73858992/211649595-c14772ae-1099-4c98-8c9e-25c031d89068.png)

Sorry this is a boring error but... I gotta do it! Going to try to install the version of INLA they used last year with something like `remotes::install_version("INLA", version="22.05.03",repos=c(getOption("repos"),INLA="https://inla.r-inla-download.org/R/testing"), dep=TRUE)` from the INLA site.
