### ISSUE TITLE
Install errors on CentOS 8 - conda environment

### ISSUE THREAD

**Issue by Jason-Conner-NOAA** [James-Thorson/FishStatsUtils#88]
For a Redhat VM (CentOS 8.7) at the AFSC, configuring installation around conda package/environment management. Packages: sf, lwgeom, terra, rgdal, raster, stars, gstat must be installed using conda repos, which are older versions of the CRAN versions of these packages (the system libs needed for these packages are not available using install.packages() in R). FishStatsUtils DESCRIPTION does not indicate version dependencies.

Using devtools::install_github("james-thorson-noaa/fishstatsutils") 
- selecting not to update the above packages does not prevent the installer from trying to update them
- adding the devtools::install arg: upgrade_dependencies=F does not change this behavior
- Error example: namespace ‘terra’ 1.5-21 is being loaded, but >= 1.6.41 is required

If version dependencies exist, please update DESCRIPTION to make this transparent, if they are just suggestions, please don't force the package updates so this can be run on a managed Linux system. I also have a ticket with OFIS to see if there is a conda workaround.

Thanks!

**Comment by James-Thorson-NOAA** [comment]
I'm not following. the DESCRIPTION does not enforce version dependencies.  

could you please list the specific file and line changes proposed?

I'll close for now, but happy to keep discussing on this thread.

**Comment by Jason-Conner-NOAA** [comment]
Apologies - this was default install behavior from devtools:
https://github.com/r-lib/devtools/issues/863

Installing all dependencies with conda install and then installing FishStatsUtils with:
devtools::install_github("james-thorson-noaa/fishstatsutils", dep=F)

succeeds, though I have yet to test it.
