### ISSUE TITLE
Cannot install `FishStatsUtils`, `rgdal` package is no longer available

### ISSUE THREAD

**Issue by jkbest2** [James-Thorson/FishStatsUtils#90]
The [R Spatial](https://r-spatial.org/) folks have been working to modernize their packages for a while (e.g. the move to `sf`). As part of this they have [retired the `rgdal`, `rgeos`, and `maptools` packages](https://r-spatial.org//r/2022/04/12/evolution.html). As of today (November 7, 2023) these packages are no longer available on CRAN. `FishStatsUtils` has `rgdal` in the `Imports` section, so it cannot currently be installed. I think that `rgdal` was taken off CRAN within the last week or two, so I wanted to give you a heads up that you may run into more folks unable to install `FishStatsUtils` soon.

[This appendix to the Spatial Data Science ebook](https://r-spatial.org/book/sp-raster.html) notes that `rgdal` should still be available from R-Forge, so this is a possible workaround.

Additional information is available in their [second](https://r-spatial.org/r/2022/12/14/evolution2.html) and [third](https://r-spatial.org/r/2023/04/10/evolution3.html) reports on the migration.

**Comment by James-Thorson-NOAA** [comment]
thanks for the reminder.  I just made a small correction to remove `rgdal` from FishStatsUtils on the dev branch (which also removes `INLA`) and will aim to do a minor version release after assessment season is done in Jan. 2024.
